// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yahoo.proto

package org.ivcode.stonks.repository.yahoo.websocket;

public final class YahooProto {
  private YahooProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Quote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string symbol = 1;</code>
     * @return Whether the symbol field is set.
     */
    boolean hasSymbol();
    /**
     * <code>optional string symbol = 1;</code>
     * @return The symbol.
     */
    java.lang.String getSymbol();
    /**
     * <code>optional string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>optional float regularMarketPrice = 2;</code>
     * @return Whether the regularMarketPrice field is set.
     */
    boolean hasRegularMarketPrice();
    /**
     * <code>optional float regularMarketPrice = 2;</code>
     * @return The regularMarketPrice.
     */
    float getRegularMarketPrice();

    /**
     * <code>optional sint64 regularMarketTime = 3;</code>
     * @return Whether the regularMarketTime field is set.
     */
    boolean hasRegularMarketTime();
    /**
     * <code>optional sint64 regularMarketTime = 3;</code>
     * @return The regularMarketTime.
     */
    long getRegularMarketTime();

    /**
     * <code>optional string currency = 4;</code>
     * @return Whether the currency field is set.
     */
    boolean hasCurrency();
    /**
     * <code>optional string currency = 4;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <code>optional string currency = 4;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>optional string exchange = 5;</code>
     * @return Whether the exchange field is set.
     */
    boolean hasExchange();
    /**
     * <code>optional string exchange = 5;</code>
     * @return The exchange.
     */
    java.lang.String getExchange();
    /**
     * <code>optional string exchange = 5;</code>
     * @return The bytes for exchange.
     */
    com.google.protobuf.ByteString
        getExchangeBytes();

    /**
     * <code>optional float regularMarketChangePercent = 8;</code>
     * @return Whether the regularMarketChangePercent field is set.
     */
    boolean hasRegularMarketChangePercent();
    /**
     * <code>optional float regularMarketChangePercent = 8;</code>
     * @return The regularMarketChangePercent.
     */
    float getRegularMarketChangePercent();

    /**
     * <code>optional sint32 regularMarketVolume = 9;</code>
     * @return Whether the regularMarketVolume field is set.
     */
    boolean hasRegularMarketVolume();
    /**
     * <code>optional sint32 regularMarketVolume = 9;</code>
     * @return The regularMarketVolume.
     */
    int getRegularMarketVolume();

    /**
     * <code>optional float regularMarketChange = 12;</code>
     * @return Whether the regularMarketChange field is set.
     */
    boolean hasRegularMarketChange();
    /**
     * <code>optional float regularMarketChange = 12;</code>
     * @return The regularMarketChange.
     */
    float getRegularMarketChange();

    /**
     * <code>optional string lastMarket = 31;</code>
     * @return Whether the lastMarket field is set.
     */
    boolean hasLastMarket();
    /**
     * <code>optional string lastMarket = 31;</code>
     * @return The lastMarket.
     */
    java.lang.String getLastMarket();
    /**
     * <code>optional string lastMarket = 31;</code>
     * @return The bytes for lastMarket.
     */
    com.google.protobuf.ByteString
        getLastMarketBytes();
  }
  /**
   * Protobuf type {@code tutorial.Quote}
   */
  public static final class Quote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Quote)
      QuoteOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Quote.newBuilder() to construct.
    private Quote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Quote() {
      symbol_ = "";
      currency_ = "";
      exchange_ = "";
      lastMarket_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Quote();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Quote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              symbol_ = bs;
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              regularMarketPrice_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              regularMarketTime_ = input.readSInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              currency_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              exchange_ = bs;
              break;
            }
            case 69: {
              bitField0_ |= 0x00000020;
              regularMarketChangePercent_ = input.readFloat();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000040;
              regularMarketVolume_ = input.readSInt32();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000080;
              regularMarketChange_ = input.readFloat();
              break;
            }
            case 250: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              lastMarket_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.internal_static_tutorial_Quote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.internal_static_tutorial_Quote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.class, org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.Builder.class);
    }

    private int bitField0_;
    public static final int SYMBOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object symbol_;
    /**
     * <code>optional string symbol = 1;</code>
     * @return Whether the symbol field is set.
     */
    @java.lang.Override
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string symbol = 1;</code>
     * @return The symbol.
     */
    @java.lang.Override
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          symbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string symbol = 1;</code>
     * @return The bytes for symbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGULARMARKETPRICE_FIELD_NUMBER = 2;
    private float regularMarketPrice_;
    /**
     * <code>optional float regularMarketPrice = 2;</code>
     * @return Whether the regularMarketPrice field is set.
     */
    @java.lang.Override
    public boolean hasRegularMarketPrice() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float regularMarketPrice = 2;</code>
     * @return The regularMarketPrice.
     */
    @java.lang.Override
    public float getRegularMarketPrice() {
      return regularMarketPrice_;
    }

    public static final int REGULARMARKETTIME_FIELD_NUMBER = 3;
    private long regularMarketTime_;
    /**
     * <code>optional sint64 regularMarketTime = 3;</code>
     * @return Whether the regularMarketTime field is set.
     */
    @java.lang.Override
    public boolean hasRegularMarketTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional sint64 regularMarketTime = 3;</code>
     * @return The regularMarketTime.
     */
    @java.lang.Override
    public long getRegularMarketTime() {
      return regularMarketTime_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 4;
    private volatile java.lang.Object currency_;
    /**
     * <code>optional string currency = 4;</code>
     * @return Whether the currency field is set.
     */
    @java.lang.Override
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string currency = 4;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currency_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string currency = 4;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGE_FIELD_NUMBER = 5;
    private volatile java.lang.Object exchange_;
    /**
     * <code>optional string exchange = 5;</code>
     * @return Whether the exchange field is set.
     */
    @java.lang.Override
    public boolean hasExchange() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string exchange = 5;</code>
     * @return The exchange.
     */
    @java.lang.Override
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exchange_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exchange = 5;</code>
     * @return The bytes for exchange.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGULARMARKETCHANGEPERCENT_FIELD_NUMBER = 8;
    private float regularMarketChangePercent_;
    /**
     * <code>optional float regularMarketChangePercent = 8;</code>
     * @return Whether the regularMarketChangePercent field is set.
     */
    @java.lang.Override
    public boolean hasRegularMarketChangePercent() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional float regularMarketChangePercent = 8;</code>
     * @return The regularMarketChangePercent.
     */
    @java.lang.Override
    public float getRegularMarketChangePercent() {
      return regularMarketChangePercent_;
    }

    public static final int REGULARMARKETVOLUME_FIELD_NUMBER = 9;
    private int regularMarketVolume_;
    /**
     * <code>optional sint32 regularMarketVolume = 9;</code>
     * @return Whether the regularMarketVolume field is set.
     */
    @java.lang.Override
    public boolean hasRegularMarketVolume() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional sint32 regularMarketVolume = 9;</code>
     * @return The regularMarketVolume.
     */
    @java.lang.Override
    public int getRegularMarketVolume() {
      return regularMarketVolume_;
    }

    public static final int REGULARMARKETCHANGE_FIELD_NUMBER = 12;
    private float regularMarketChange_;
    /**
     * <code>optional float regularMarketChange = 12;</code>
     * @return Whether the regularMarketChange field is set.
     */
    @java.lang.Override
    public boolean hasRegularMarketChange() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional float regularMarketChange = 12;</code>
     * @return The regularMarketChange.
     */
    @java.lang.Override
    public float getRegularMarketChange() {
      return regularMarketChange_;
    }

    public static final int LASTMARKET_FIELD_NUMBER = 31;
    private volatile java.lang.Object lastMarket_;
    /**
     * <code>optional string lastMarket = 31;</code>
     * @return Whether the lastMarket field is set.
     */
    @java.lang.Override
    public boolean hasLastMarket() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string lastMarket = 31;</code>
     * @return The lastMarket.
     */
    @java.lang.Override
    public java.lang.String getLastMarket() {
      java.lang.Object ref = lastMarket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastMarket_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastMarket = 31;</code>
     * @return The bytes for lastMarket.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastMarketBytes() {
      java.lang.Object ref = lastMarket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastMarket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, symbol_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, regularMarketPrice_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeSInt64(3, regularMarketTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currency_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exchange_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeFloat(8, regularMarketChangePercent_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeSInt32(9, regularMarketVolume_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeFloat(12, regularMarketChange_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 31, lastMarket_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, symbol_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, regularMarketPrice_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, regularMarketTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currency_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exchange_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, regularMarketChangePercent_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(9, regularMarketVolume_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, regularMarketChange_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(31, lastMarket_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote)) {
        return super.equals(obj);
      }
      org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote other = (org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote) obj;

      if (hasSymbol() != other.hasSymbol()) return false;
      if (hasSymbol()) {
        if (!getSymbol()
            .equals(other.getSymbol())) return false;
      }
      if (hasRegularMarketPrice() != other.hasRegularMarketPrice()) return false;
      if (hasRegularMarketPrice()) {
        if (java.lang.Float.floatToIntBits(getRegularMarketPrice())
            != java.lang.Float.floatToIntBits(
                other.getRegularMarketPrice())) return false;
      }
      if (hasRegularMarketTime() != other.hasRegularMarketTime()) return false;
      if (hasRegularMarketTime()) {
        if (getRegularMarketTime()
            != other.getRegularMarketTime()) return false;
      }
      if (hasCurrency() != other.hasCurrency()) return false;
      if (hasCurrency()) {
        if (!getCurrency()
            .equals(other.getCurrency())) return false;
      }
      if (hasExchange() != other.hasExchange()) return false;
      if (hasExchange()) {
        if (!getExchange()
            .equals(other.getExchange())) return false;
      }
      if (hasRegularMarketChangePercent() != other.hasRegularMarketChangePercent()) return false;
      if (hasRegularMarketChangePercent()) {
        if (java.lang.Float.floatToIntBits(getRegularMarketChangePercent())
            != java.lang.Float.floatToIntBits(
                other.getRegularMarketChangePercent())) return false;
      }
      if (hasRegularMarketVolume() != other.hasRegularMarketVolume()) return false;
      if (hasRegularMarketVolume()) {
        if (getRegularMarketVolume()
            != other.getRegularMarketVolume()) return false;
      }
      if (hasRegularMarketChange() != other.hasRegularMarketChange()) return false;
      if (hasRegularMarketChange()) {
        if (java.lang.Float.floatToIntBits(getRegularMarketChange())
            != java.lang.Float.floatToIntBits(
                other.getRegularMarketChange())) return false;
      }
      if (hasLastMarket() != other.hasLastMarket()) return false;
      if (hasLastMarket()) {
        if (!getLastMarket()
            .equals(other.getLastMarket())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSymbol()) {
        hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getSymbol().hashCode();
      }
      if (hasRegularMarketPrice()) {
        hash = (37 * hash) + REGULARMARKETPRICE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRegularMarketPrice());
      }
      if (hasRegularMarketTime()) {
        hash = (37 * hash) + REGULARMARKETTIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRegularMarketTime());
      }
      if (hasCurrency()) {
        hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
        hash = (53 * hash) + getCurrency().hashCode();
      }
      if (hasExchange()) {
        hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
        hash = (53 * hash) + getExchange().hashCode();
      }
      if (hasRegularMarketChangePercent()) {
        hash = (37 * hash) + REGULARMARKETCHANGEPERCENT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRegularMarketChangePercent());
      }
      if (hasRegularMarketVolume()) {
        hash = (37 * hash) + REGULARMARKETVOLUME_FIELD_NUMBER;
        hash = (53 * hash) + getRegularMarketVolume();
      }
      if (hasRegularMarketChange()) {
        hash = (37 * hash) + REGULARMARKETCHANGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRegularMarketChange());
      }
      if (hasLastMarket()) {
        hash = (37 * hash) + LASTMARKET_FIELD_NUMBER;
        hash = (53 * hash) + getLastMarket().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Quote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Quote)
        org.ivcode.stonks.repository.yahoo.websocket.YahooProto.QuoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.internal_static_tutorial_Quote_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.internal_static_tutorial_Quote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.class, org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.Builder.class);
      }

      // Construct using org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        regularMarketPrice_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        regularMarketTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        currency_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        exchange_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        regularMarketChangePercent_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        regularMarketVolume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        regularMarketChange_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastMarket_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.internal_static_tutorial_Quote_descriptor;
      }

      @java.lang.Override
      public org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote getDefaultInstanceForType() {
        return org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.getDefaultInstance();
      }

      @java.lang.Override
      public org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote build() {
        org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote buildPartial() {
        org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote result = new org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.symbol_ = symbol_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.regularMarketPrice_ = regularMarketPrice_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.regularMarketTime_ = regularMarketTime_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.currency_ = currency_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.exchange_ = exchange_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.regularMarketChangePercent_ = regularMarketChangePercent_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.regularMarketVolume_ = regularMarketVolume_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.regularMarketChange_ = regularMarketChange_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastMarket_ = lastMarket_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote) {
          return mergeFrom((org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote other) {
        if (other == org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote.getDefaultInstance()) return this;
        if (other.hasSymbol()) {
          bitField0_ |= 0x00000001;
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.hasRegularMarketPrice()) {
          setRegularMarketPrice(other.getRegularMarketPrice());
        }
        if (other.hasRegularMarketTime()) {
          setRegularMarketTime(other.getRegularMarketTime());
        }
        if (other.hasCurrency()) {
          bitField0_ |= 0x00000008;
          currency_ = other.currency_;
          onChanged();
        }
        if (other.hasExchange()) {
          bitField0_ |= 0x00000010;
          exchange_ = other.exchange_;
          onChanged();
        }
        if (other.hasRegularMarketChangePercent()) {
          setRegularMarketChangePercent(other.getRegularMarketChangePercent());
        }
        if (other.hasRegularMarketVolume()) {
          setRegularMarketVolume(other.getRegularMarketVolume());
        }
        if (other.hasRegularMarketChange()) {
          setRegularMarketChange(other.getRegularMarketChange());
        }
        if (other.hasLastMarket()) {
          bitField0_ |= 0x00000100;
          lastMarket_ = other.lastMarket_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object symbol_ = "";
      /**
       * <code>optional string symbol = 1;</code>
       * @return Whether the symbol field is set.
       */
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string symbol = 1;</code>
       * @return The symbol.
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            symbol_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string symbol = 1;</code>
       * @return The bytes for symbol.
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string symbol = 1;</code>
       * @param value The symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string symbol = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>optional string symbol = 1;</code>
       * @param value The bytes for symbol to set.
       * @return This builder for chaining.
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }

      private float regularMarketPrice_ ;
      /**
       * <code>optional float regularMarketPrice = 2;</code>
       * @return Whether the regularMarketPrice field is set.
       */
      @java.lang.Override
      public boolean hasRegularMarketPrice() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional float regularMarketPrice = 2;</code>
       * @return The regularMarketPrice.
       */
      @java.lang.Override
      public float getRegularMarketPrice() {
        return regularMarketPrice_;
      }
      /**
       * <code>optional float regularMarketPrice = 2;</code>
       * @param value The regularMarketPrice to set.
       * @return This builder for chaining.
       */
      public Builder setRegularMarketPrice(float value) {
        bitField0_ |= 0x00000002;
        regularMarketPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float regularMarketPrice = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegularMarketPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        regularMarketPrice_ = 0F;
        onChanged();
        return this;
      }

      private long regularMarketTime_ ;
      /**
       * <code>optional sint64 regularMarketTime = 3;</code>
       * @return Whether the regularMarketTime field is set.
       */
      @java.lang.Override
      public boolean hasRegularMarketTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional sint64 regularMarketTime = 3;</code>
       * @return The regularMarketTime.
       */
      @java.lang.Override
      public long getRegularMarketTime() {
        return regularMarketTime_;
      }
      /**
       * <code>optional sint64 regularMarketTime = 3;</code>
       * @param value The regularMarketTime to set.
       * @return This builder for chaining.
       */
      public Builder setRegularMarketTime(long value) {
        bitField0_ |= 0x00000004;
        regularMarketTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 regularMarketTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegularMarketTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        regularMarketTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>optional string currency = 4;</code>
       * @return Whether the currency field is set.
       */
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string currency = 4;</code>
       * @return The currency.
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            currency_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string currency = 4;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string currency = 4;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string currency = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000008);
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>optional string currency = 4;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        currency_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchange_ = "";
      /**
       * <code>optional string exchange = 5;</code>
       * @return Whether the exchange field is set.
       */
      public boolean hasExchange() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string exchange = 5;</code>
       * @return The exchange.
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exchange_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exchange = 5;</code>
       * @return The bytes for exchange.
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exchange = 5;</code>
       * @param value The exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchange = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearExchange() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exchange = 5;</code>
       * @param value The bytes for exchange to set.
       * @return This builder for chaining.
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exchange_ = value;
        onChanged();
        return this;
      }

      private float regularMarketChangePercent_ ;
      /**
       * <code>optional float regularMarketChangePercent = 8;</code>
       * @return Whether the regularMarketChangePercent field is set.
       */
      @java.lang.Override
      public boolean hasRegularMarketChangePercent() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional float regularMarketChangePercent = 8;</code>
       * @return The regularMarketChangePercent.
       */
      @java.lang.Override
      public float getRegularMarketChangePercent() {
        return regularMarketChangePercent_;
      }
      /**
       * <code>optional float regularMarketChangePercent = 8;</code>
       * @param value The regularMarketChangePercent to set.
       * @return This builder for chaining.
       */
      public Builder setRegularMarketChangePercent(float value) {
        bitField0_ |= 0x00000020;
        regularMarketChangePercent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float regularMarketChangePercent = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegularMarketChangePercent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        regularMarketChangePercent_ = 0F;
        onChanged();
        return this;
      }

      private int regularMarketVolume_ ;
      /**
       * <code>optional sint32 regularMarketVolume = 9;</code>
       * @return Whether the regularMarketVolume field is set.
       */
      @java.lang.Override
      public boolean hasRegularMarketVolume() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional sint32 regularMarketVolume = 9;</code>
       * @return The regularMarketVolume.
       */
      @java.lang.Override
      public int getRegularMarketVolume() {
        return regularMarketVolume_;
      }
      /**
       * <code>optional sint32 regularMarketVolume = 9;</code>
       * @param value The regularMarketVolume to set.
       * @return This builder for chaining.
       */
      public Builder setRegularMarketVolume(int value) {
        bitField0_ |= 0x00000040;
        regularMarketVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 regularMarketVolume = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegularMarketVolume() {
        bitField0_ = (bitField0_ & ~0x00000040);
        regularMarketVolume_ = 0;
        onChanged();
        return this;
      }

      private float regularMarketChange_ ;
      /**
       * <code>optional float regularMarketChange = 12;</code>
       * @return Whether the regularMarketChange field is set.
       */
      @java.lang.Override
      public boolean hasRegularMarketChange() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional float regularMarketChange = 12;</code>
       * @return The regularMarketChange.
       */
      @java.lang.Override
      public float getRegularMarketChange() {
        return regularMarketChange_;
      }
      /**
       * <code>optional float regularMarketChange = 12;</code>
       * @param value The regularMarketChange to set.
       * @return This builder for chaining.
       */
      public Builder setRegularMarketChange(float value) {
        bitField0_ |= 0x00000080;
        regularMarketChange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float regularMarketChange = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegularMarketChange() {
        bitField0_ = (bitField0_ & ~0x00000080);
        regularMarketChange_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object lastMarket_ = "";
      /**
       * <code>optional string lastMarket = 31;</code>
       * @return Whether the lastMarket field is set.
       */
      public boolean hasLastMarket() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string lastMarket = 31;</code>
       * @return The lastMarket.
       */
      public java.lang.String getLastMarket() {
        java.lang.Object ref = lastMarket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastMarket_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastMarket = 31;</code>
       * @return The bytes for lastMarket.
       */
      public com.google.protobuf.ByteString
          getLastMarketBytes() {
        java.lang.Object ref = lastMarket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastMarket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastMarket = 31;</code>
       * @param value The lastMarket to set.
       * @return This builder for chaining.
       */
      public Builder setLastMarket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastMarket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastMarket = 31;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastMarket() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastMarket_ = getDefaultInstance().getLastMarket();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastMarket = 31;</code>
       * @param value The bytes for lastMarket to set.
       * @return This builder for chaining.
       */
      public Builder setLastMarketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastMarket_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Quote)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Quote)
    private static final org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote();
    }

    public static org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Quote>
        PARSER = new com.google.protobuf.AbstractParser<Quote>() {
      @java.lang.Override
      public Quote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Quote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Quote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quote> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.ivcode.stonks.repository.yahoo.websocket.YahooProto.Quote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Quote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Quote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013yahoo.proto\022\010tutorial\"\344\001\n\005Quote\022\016\n\006sym" +
      "bol\030\001 \001(\t\022\032\n\022regularMarketPrice\030\002 \001(\002\022\031\n" +
      "\021regularMarketTime\030\003 \001(\022\022\020\n\010currency\030\004 \001" +
      "(\t\022\020\n\010exchange\030\005 \001(\t\022\"\n\032regularMarketCha" +
      "ngePercent\030\010 \001(\002\022\033\n\023regularMarketVolume\030" +
      "\t \001(\021\022\033\n\023regularMarketChange\030\014 \001(\002\022\022\n\nla" +
      "stMarket\030\037 \001(\tB:\n,org.ivcode.stonks.repo" +
      "sitory.yahoo.websocketB\nYahooProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Quote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Quote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Quote_descriptor,
        new java.lang.String[] { "Symbol", "RegularMarketPrice", "RegularMarketTime", "Currency", "Exchange", "RegularMarketChangePercent", "RegularMarketVolume", "RegularMarketChange", "LastMarket", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
